<?php
    require("lib/mysql.lib.php");
    require("lib/setting.lib.php");
    require("lib/fileupload.lib.php");
    require("lib/pager.lib.php");
    require("lib/page.lib.php");
    require("data/mysql_connect.php");
    require("lib/functions.php");
    require("lib/formelements.php");
?>